In [112]:
import requests
import json
import time
import pandas as pd

In [258]:
# segments boundaries: split territory on the equal horizontal slices

bounds = {
    1: {'north': 41.425507, 'south': 41.377552767, 'east': -73.052983, 'west': -74.948125},
    2: {'north': 41.377552766, 'south': 41.329598533, 'east': -73.052983, 'west': -74.948125},
    3: {'north': 41.329598532, 'south': 41.2816443, 'east': -73.052983, 'west': -74.948125},
    4: {'north': 41.281644299, 'south': 41.233690067, 'east': -73.052983, 'west': -74.948125},
    5: {'north': 41.233690066, 'south': 41.185735833, 'east': -73.052983, 'west': -74.948125},
    6: {'north': 41.185735832, 'south': 41.1377816, 'east': -73.052983, 'west': -74.948125},
    7: {'north': 41.137781599, 'south': 41.089827367, 'east': -73.052983, 'west': -74.948125},
    8: {'north': 41.089827366, 'south': 41.041873133, 'east': -73.052983, 'west': -74.948125},
    9: {'north': 41.041873132, 'south': 40.9939189, 'east': -73.052983, 'west': -74.948125},
    10: {'north': 40.993918899, 'south': 40.945964667, 'east': -73.052983, 'west': -74.948125},
    11: {'north': 40.945964666, 'south': 40.898010433, 'east': -73.052983, 'west': -74.948125},
    12: {'north': 40.898010432, 'south': 40.890787764, 'east': -73.052983, 'west': -74.948125},
    13: {'north': 40.890787763, 'south': 40.883565095, 'east': -73.052983, 'west': -74.948125},
    14: {'north': 40.883565094, 'south': 40.876342426, 'east': -73.052983, 'west': -74.948125},
    15: {'north': 40.876342425, 'south': 40.869119757, 'east': -73.052983, 'west': -74.948125},
    16: {'north': 40.869119756, 'south': 40.861897088, 'east': -73.052983, 'west': -74.948125},
    17: {'north': 40.861897087, 'south': 40.854674419, 'east': -73.052983, 'west': -74.948125},
    18: {'north': 40.854674418, 'south': 40.847451751, 'east': -73.052983, 'west': -74.948125},
    19: {'north': 40.84745175, 'south': 40.840229082, 'east': -73.052983, 'west': -74.948125},
    20: {'north': 40.840229081, 'south': 40.833006413, 'east': -73.052983, 'west': -74.948125},
    21: {'north': 40.833006412, 'south': 40.825783744, 'east': -73.052983, 'west': -74.948125},
    22: {'north': 40.825783743, 'south': 40.818561075, 'east': -73.052983, 'west': -74.948125},
    23: {'north': 40.818561074, 'south': 40.811338407, 'east': -73.052983, 'west': -74.948125},
    24: {'north': 40.811338406, 'south': 40.804115738, 'east': -73.052983, 'west': -74.948125},
    25: {'north': 40.804115737, 'south': 40.796893069, 'east': -73.052983, 'west': -74.948125},
    26: {'north': 40.796893068, 'south': 40.7896704, 'east': -73.052983, 'west': -74.948125},
    27: {'north': 40.789670399, 'south': 40.782447731, 'east': -73.052983, 'west': -74.948125},
    28: {'north': 40.78244773, 'south': 40.775225062, 'east': -73.052983, 'west': -74.948125},
    29: {'north': 40.775225061, 'south': 40.768002394, 'east': -73.052983, 'west': -74.948125},
    30: {'north': 40.768002393, 'south': 40.760779725, 'east': -73.052983, 'west': -74.948125},
    31: {'north': 40.760779724, 'south': 40.753557056, 'east': -73.052983, 'west': -74.948125},
    32: {'north': 40.753557055, 'south': 40.746334387, 'east': -73.052983, 'west': -74.948125},
    33: {'north': 40.746334386, 'south': 40.739111718, 'east': -73.052983, 'west': -74.948125},
    34: {'north': 40.739111717, 'south': 40.73188905, 'east': -73.052983, 'west': -74.948125},
    35: {'north': 40.731889049, 'south': 40.724666381, 'east': -73.052983, 'west': -74.948125},
    36: {'north': 40.72466638, 'south': 40.717443712, 'east': -73.052983, 'west': -74.948125},
    37: {'north': 40.717443711, 'south': 40.710221043, 'east': -73.052983, 'west': -74.948125},
    38: {'north': 40.710221042, 'south': 40.702998374, 'east': -73.052983, 'west': -74.948125},
    39: {'north': 40.702998373, 'south': 40.695775705, 'east': -73.052983, 'west': -74.948125},
    40: {'north': 40.695775704, 'south': 40.688553037, 'east': -73.052983, 'west': -74.948125},
    41: {'north': 40.688553036, 'south': 40.681330368, 'east': -73.052983, 'west': -74.948125},
    42: {'north': 40.681330367, 'south': 40.674107699, 'east': -73.052983, 'west': -74.948125},
    43: {'north': 40.674107698, 'south': 40.66688503, 'east': -73.052983, 'west': -74.948125},
    44: {'north': 40.666885029, 'south': 40.659662361, 'east': -73.052983, 'west': -74.948125},
    45: {'north': 40.65966236, 'south': 40.652439692, 'east': -73.052983, 'west': -74.948125},
    46: {'north': 40.652439691, 'south': 40.645217024, 'east': -73.052983, 'west': -74.948125},
    47: {'north': 40.645217023, 'south': 40.637994355, 'east': -73.052983, 'west': -74.948125},
    48: {'north': 40.637994354, 'south': 40.630771686, 'east': -73.052983, 'west': -74.948125},
    49: {'north': 40.630771685, 'south': 40.623549017, 'east': -73.052983, 'west': -74.948125},
    50: {'north': 40.623549016, 'south': 40.616326348, 'east': -73.052983, 'west': -74.948125},
    51: {'north': 40.616326347, 'south': 40.60910368, 'east': -73.052983, 'west': -74.948125},
    52: {'north': 40.609103679, 'south': 40.601881011, 'east': -73.052983, 'west': -74.948125},
    53: {'north': 40.60188101, 'south': 40.594658342, 'east': -73.052983, 'west': -74.948125},
    54: {'north': 40.594658341, 'south': 40.587435673, 'east': -73.052983, 'west': -74.948125},
    55: {'north': 40.587435672, 'south': 40.580213004, 'east': -73.052983, 'west': -74.948125},
    56: {'north': 40.580213003, 'south': 40.572990335, 'east': -73.052983, 'west': -74.948125},
    57: {'north': 40.572990334, 'south': 40.565767667, 'east': -73.052983, 'west': -74.948125},
    58: {'north': 40.565767666, 'south': 40.558544998, 'east': -73.052983, 'west': -74.948125},
    59: {'north': 40.558544997, 'south': 40.551322329, 'east': -73.052983, 'west': -74.948125},
    60: {'north': 40.551322328, 'south': 40.54409966, 'east': -73.052983, 'west': -74.948125},
    61: {'north': 40.544099659, 'south': 40.536876991, 'east': -73.052983, 'west': -74.948125},
    62: {'north': 40.53687699, 'south': 40.529654323, 'east': -73.052983, 'west': -74.948125},
    63: {'north': 40.529654322, 'south': 40.522431654, 'east': -73.052983, 'west': -74.948125},
    64: {'north': 40.522431653, 'south': 40.515208985, 'east': -73.052983, 'west': -74.948125},
    65: {'north': 40.515208984, 'south': 40.507986316, 'east': -73.052983, 'west': -74.948125},
    66: {'north': 40.507986315, 'south': 40.500763647, 'east': -73.052983, 'west': -74.948125},
    67: {'north': 40.500763646, 'south': 40.493540978, 'east': -73.052983, 'west': -74.948125},
    68: {'north': 40.493540977, 'south': 40.48631831, 'east': -73.052983, 'west': -74.948125},
    69: {'north': 40.486318309, 'south': 40.479095641, 'east': -73.052983, 'west': -74.948125},
    70: {'north': 40.47909564, 'south': 39.98688, 'east': -73.052983, 'west': -74.948125}
}

In [269]:
def make_top_url(bounds, request_id):
    part_1 = 'https://www.zillow.com/search/GetSearchPageState.htm?searchQueryState={"pagination":{},"mapBounds":{'
    part_2 = '"west":{west},"east":{east},"south":{south},"north":{north}'.format(**bounds)
    part_3 = '},"isMapVisible":true,"filterState":{"isPreMarketForeclosure":{"value":false},"isForSaleForeclosure":{"value":false},"isMultiFamily":{"value":false},"isAllHomes":{"value":true},"isAuction":{"value":false},"isNewConstruction":{"value":false},"isForRent":{"value":true},"isLotLand":{"value":false},"isManufactured":{"value":false},"isForSaleByOwner":{"value":false},"isComingSoon":{"value":false},"isPreMarketPreForeclosure":{"value":false},"isForSaleByAgent":{"value":false}},"isListVisible":true,"mapZoom":9}&wants={"cat1":["mapResults"]}&requestId='
    
    return part_1 + part_2 + part_3 + str(request_id)


def make_raw_data(zpid):
    raw_data = {"operationName":"ForRentDoubleScrollFullRenderQuery","variables":{"zpid":zpid,"contactFormRenderParameter":{"zpid":zpid,"platform":"desktop","isDoubleScroll":True}},"clientVersion":"home-details/6.0.11.0.0.hotfix-11-23-2020.d69fab8","queryId":"172653a956cf8fb0836010e71b7385e9"}
    
    return raw_data


def make_low_url(zpid):
    low_url_template = 'https://www.zillow.com/graphql/?zpid={}&contactFormRenderParameter=&queryId=172653a956cf8fb0836010e71b7385e9&operationName=ForRentDoubleScrollFullRenderQuery'

    return low_url_template.format(zpid)

In [270]:
headers_top = {
    'Host': 'www.zillow.com',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:83.0) Gecko/20100101 Firefox/83.0',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'keep-alive',
    'Upgrade-Insecure-Requests': '1',
    'Cache-Control': 'max-age=0'
}


headers_low = {
    'Host': 'www.zillow.com',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:83.0) Gecko/20100101 Firefox/83.0',
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.5',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'keep-alive',
    'content-type': 'text/plain',
    'Origin': 'https://www.zillow.com'
}

In [271]:
def transform_data(raw_details, zpid):
    # function transforms json details to data frame format

    # high level details
    high_level_raw = raw_details.json()['data']['property']

    high_level_dict = {'zpid': [zpid]}
    hig_level_props = ['city', 'homeStatus', 'price', 'streetAddress', 'datePosted', 'zipcode', 'latitude', 'longitude']
    for k in hig_level_props:
        high_level_dict[k] = [high_level_raw[k]]

    df_h = pd.DataFrame.from_dict(high_level_dict, orient='columns', dtype=None, columns=None)



    # low level details
    low_level_raw = raw_details.json()['data']['property']['resoFacts']

    low_level_dict = {'zpid': [zpid]}
    for k in low_level_raw.keys():
        value = low_level_raw[k]

        if type(value) != dict and k not in ['otherFacts', 'atAGlanceFacts']:
            if type(value) == list:
                try:
                    value = ' | '.join(value)
                except:
                    value = None
                    continue

            low_level_dict[k] = [value]

    df_l = pd.DataFrame.from_dict(low_level_dict, orient='columns', dtype=None, columns=None)
    
    return df_h.merge(df_l, on='zpid')

In [272]:
df_all = pd.DataFrame()


broken_segments = []
broken_objects = []

for segment in bounds.keys():
    url_top = make_top_url(bounds[segment], segment)
    response_top = requests.get(url_top, headers=headers_top)

    if response_top.status_code != 200:
        time.sleep(60)
        response_top = requests.get(url_top, headers=headers_top)

    try:
        if response_top.status_code != 200:
            broken_segments.append(segment)

        else:
            
            if 'totalResultCount' in response_top.json()['cat1']['searchList'].keys():
                total_results = response_top.json()['cat1']['searchList']['totalResultCount']
            else:
                total_results = 'unknown'
                
            print('Segment: {}, Total objects: {}'.format(segment, total_results))
            for result in response_top.json()['cat1']['searchResults']['mapResults']:
                if 'zpid' in result.keys():
                    zpid = result['zpid']
                    

                    url_low = make_low_url(zpid)
                    raw_data = make_raw_data(zpid)
                    raw_details = requests.post(url_low, headers=headers_low, json=raw_data)

                    if raw_details.status_code != 200:
                        time.sleep(60)
                        raw_details = requests.post(url_low, headers=headers_low, json=raw_data)

                    try:
                        if raw_details.status_code != 200:
                            broken_objects.append(zpid)

                        else:
                            df_part = transform_data(raw_details, zpid)
                            df_all = df_all.append(df_part)

                    except:
                        continue

                    time.sleep(2)

            print('Cumulative data size: {}'.format(len(df_all)))

    except:
        continue


df_all.to_csv('zillow_rent_new_york.csv')

Segment: 1, Total objects: 68
Cumulative data size: 59
Segment: 2, Total objects: 70
Cumulative data size: 122
Segment: 3, Total objects: 79
Cumulative data size: 194
Segment: 4, Total objects: 62
Cumulative data size: 249
Segment: 5, Total objects: 165
Cumulative data size: 394
Segment: 6, Total objects: 234
Cumulative data size: 598
Segment: 7, Total objects: 254
Cumulative data size: 806
Segment: 8, Total objects: 382
Cumulative data size: 1097
Segment: 9, Total objects: 419
Cumulative data size: 1429
Segment: 10, Total objects: 315
Cumulative data size: 1684
Segment: 11, Total objects: 676
Cumulative data size: 2080
Segment: 12, Total objects: 114
Cumulative data size: 2173
Segment: 13, Total objects: 147
Cumulative data size: 2285
Segment: 14, Total objects: 165
Cumulative data size: 2420
Segment: 15, Total objects: 184
Cumulative data size: 2579
Segment: 16, Total objects: 214
Cumulative data size: 2749
Segment: 17, Total objects: 215
Cumulative data size: 2915
Segment: 18, Total objects: 317
Cumulative data size: 3153
Segment: 19, Total objects: 271
Cumulative data size: 3380
Segment: 20, Total objects: 275
Cumulative data size: 3595
Segment: 21, Total objects: 308
Cumulative data size: 3836
Segment: 22, Total objects: 354
Cumulative data size: 4107
Segment: 23, Total objects: 321
Cumulative data size: 4350
Segment: 24, Total objects: 424
Cumulative data size: 4676
Segment: 25, Total objects: 571
Cumulative data size: 5002
Segment: 26, Total objects: 598
Cumulative data size: 5320
Segment: 27, Total objects: 880
Cumulative data size: 5625
Segment: 28, Total objects: 1229
Cumulative data size: 5885
Segment: 29, Total objects: 1235
Cumulative data size: 6190
Segment: 30, Total objects: 1454
Cumulative data size: 6491
Segment: 31, Total objects: 1082
Cumulative data size: 6785
Segment: 32, Total objects: 1150
Cumulative data size: 7029
Segment: 33, Total objects: 1674
Cumulative data size: 7282
Segment: 34, Total objects: 1341
Cumulative data size: 7563
Segment: 35, Total objects: 1610
Segment: 36, Total objects: 1694
Cumulative data size: 7906
Segment: 37, Total objects: 1190
Cumulative data size: 8191
Segment: 38, Total objects: 926
Cumulative data size: 8494
Segment: 39, Total objects: 713
Cumulative data size: 8857
Segment: 40, Total objects: 918
Cumulative data size: 9202
Segment: 41, Total objects: 1033
Cumulative data size: 9565
Segment: 42, Total objects: 908
Cumulative data size: 9949
Segment: 43, Total objects: 663
Cumulative data size: 10351
Segment: 44, Total objects: 506
Cumulative data size: 10763
Segment: 45, Total objects: 390
Cumulative data size: 11089
Segment: 46, Total objects: 347
Cumulative data size: 11390
Segment: 47, Total objects: 239
Cumulative data size: 11586
Segment: 48, Total objects: 224
Cumulative data size: 11765
Segment: 49, Total objects: 157
Cumulative data size: 11897
Segment: 50, Total objects: 207
Cumulative data size: 12079
Segment: 51, Total objects: 150
Cumulative data size: 12210
Segment: 52, Total objects: 151
Cumulative data size: 12338
Segment: 53, Total objects: 112
Cumulative data size: 12430
Segment: 54, Total objects: 154
Cumulative data size: 12571
Segment: 55, Total objects: 139
Cumulative data size: 12686
Segment: 56, Total objects: 86
Cumulative data size: 12757
Segment: 57, Total objects: 72
Cumulative data size: 12808
Segment: 58, Total objects: 43
Cumulative data size: 12839
Segment: 59, Total objects: 53
Cumulative data size: 12887
Segment: 60, Total objects: 53
Cumulative data size: 12933
Segment: 61, Total objects: 38
Cumulative data size: 12965
Segment: 62, Total objects: 33
Cumulative data size: 12993
Segment: 63, Total objects: 30
Cumulative data size: 13018
Segment: 64, Total objects: 20
Cumulative data size: 13030
Segment: 65, Total objects: 27
Cumulative data size: 13052
Segment: 66, Total objects: 41
Cumulative data size: 13082
Segment: 67, Total objects: 39
Cumulative data size: 13100
Segment: 68, Total objects: 17
Cumulative data size: 13109
Segment: 69, Total objects: 7
Cumulative data size: 13115
Segment: 70, Total objects: 1149
Cumulative data size: 13490